- name: configure DB server
  hosts: localhost
  become: yes
  vars:
    login_host: localhost
  # vars_prompt:
  #   - name: mysql_root_password
  #     prompt: enter MYSQL root_password
  #     private: no
  tasks:
  - name: Install MYSQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: Start and Enable my sql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
# check password is already setup or not
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: conn_output
  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{conn_output}}"
      

